version: '3.8'

services:
  websocket-server:
    # Указываем путь к Dockerfile
    build:
      context: .
    # Подключаем текущую директорию как том
    volumes:
      - .:/app
    # Указываем рабочую директорию внутри контейнера
    working_dir: /app
    # Команда запуска WebSocket-сервера
    command: ["node", "server.js"]
    # Открываем порт 3001
    ports:
      - "3001:3001"
    # Подключаем к сети Laravel Sail
    networks:
      - app-crm_sail

networks:
  app-crm_sail:
    external: true
